name: Test

on:
  deployment:
  deployment_status:
    branch:
      - test-deploy-status

jobs:
  print-status:
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment status
        run: |
          echo "Deployment status: ${{ github.event.deployment_status.state }}"
