name: Test

on:
  check_run:
    types: [created, completed]
    branch:
      - test-deploy-status
  check_suite:
    types: [completed]
    branch:
      - test-deploy-status

jobs:
  print-status:
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment status
        run: |
          echo "Event payload: ${{ toJson(github.event) }}"
