name: Test

on:
  repository_dispatch:
    types:

jobs:
  print-status:
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment status
        run: |
          echo "Event payload: ${{ toJson(github.event) }}"
