name: Test

on:
  issue_comment:
    types: [created, edited]
    branch:
      - test-deploy-status

jobs:
  print-status:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment status
        run: |
          echo "Event payload: ${{ toJson(github.event) }}"
